spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itend/springcloud-examples/
          search-paths: config-repo
          username: 
          password: 
server:
  port: 9999
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/